# Generated by Django 2.0.13 on 2020-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
